version: '3.9'

networks:
  funcnet:
    name: funcnet
    driver: bridge

services:
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra
    networks:
      - funcnet