## Users

POST http://localhost:8002/v1/users  
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2TTBsOHFPWU5mMFlGUmhTMm1JTiJ9.eyJpc3MiOiJodHRwczovL2Rldi1mdXVleWdrcno4MWJpcml4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJaZEVvRVE5ZlJsc09YMms2QWNkNzBiYkZVVjBJMnZXWUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnQudGlja2V0ZXguY29tIiwiaWF0IjoxNjg5NjE4NzkwLCJleHAiOjE2ODk3MDUxOTAsImF6cCI6IlpkRW9FUTlmUmxzT1gyazZBY2Q3MGJiRlVWMEkydldZIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.JiFE-Oxq0LvFWaz2zlV2W3ABpqPepmvY3NPwyuMk2nDJeggEHK0JhK7akancXl6WOPdHnjUeb-fc3inZZDGcrQbH0tb8bt7rJ-xQG21JHfhU16djbWAlxlaJjaXG9mFZ4QSBtLGhBQzSqesw2VnOx7OixlcHBEziiIEC6QUeai2FxvYTN56UF0yBoWiLyhD63jeRhv9bQLZ__FJWeCgfDBe4I9IZZHbocrgZdEKP99bCRH5m9YB5PVXFn1dc--xD0Ed5WYISt7p2xTE-mORRa4VCEt0iV0ylxOzXCWJlNGFowpphQspIHxvSuawuFl_IKggml78drDia7Y8mheb0Vg
Content-Type: application/json 

{
  "id": "string",
  "email": "string",
  "fullname": "string",
  "phone": "string",
  "ext_id": "string",
  "preferences": [
    {
      "channels": [
        {
          "value": "string",
          "channel_type": "email",
          "message_type": "tickets"
        }
      ]
    }
  ],
  "address": {
    "zipcode": "string",
    "street1": "string",
    "street2": "string",
    "country": "string",
    "state": "string"
  }
} 
###

###
POST http://localhost:8000/v1/adventures
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2TTBsOHFPWU5mMFlGUmhTMm1JTiJ9.eyJpc3MiOiJodHRwczovL2Rldi1mdXVleWdrcno4MWJpcml4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJaZEVvRVE5ZlJsc09YMms2QWNkNzBiYkZVVjBJMnZXWUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnQudGlja2V0ZXguY29tIiwiaWF0IjoxNjg5NjE4NzkwLCJleHAiOjE2ODk3MDUxOTAsImF6cCI6IlpkRW9FUTlmUmxzT1gyazZBY2Q3MGJiRlVWMEkydldZIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.JiFE-Oxq0LvFWaz2zlV2W3ABpqPepmvY3NPwyuMk2nDJeggEHK0JhK7akancXl6WOPdHnjUeb-fc3inZZDGcrQbH0tb8bt7rJ-xQG21JHfhU16djbWAlxlaJjaXG9mFZ4QSBtLGhBQzSqesw2VnOx7OixlcHBEziiIEC6QUeai2FxvYTN56UF0yBoWiLyhD63jeRhv9bQLZ__FJWeCgfDBe4I9IZZHbocrgZdEKP99bCRH5m9YB5PVXFn1dc--xD0Ed5WYISt7p2xTE-mORRa4VCEt0iV0ylxOzXCWJlNGFowpphQspIHxvSuawuFl_IKggml78drDia7Y8mheb0Vg
content-type:application/json

{
  "name": "string1",
  "description": "string",
  "tickets": [
    {
      "capacity": 0,
      "type": "string"
    }
  ],
  "venue_id": "aaa"
}
###
POST http://localhost:8001/v1/venues 
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2TTBsOHFPWU5mMFlGUmhTMm1JTiJ9.eyJpc3MiOiJodHRwczovL2Rldi1mdXVleWdrcno4MWJpcml4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJaZEVvRVE5ZlJsc09YMms2QWNkNzBiYkZVVjBJMnZXWUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnQudGlja2V0ZXguY29tIiwiaWF0IjoxNjg5NjE4NzkwLCJleHAiOjE2ODk3MDUxOTAsImF6cCI6IlpkRW9FUTlmUmxzT1gyazZBY2Q3MGJiRlVWMEkydldZIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.JiFE-Oxq0LvFWaz2zlV2W3ABpqPepmvY3NPwyuMk2nDJeggEHK0JhK7akancXl6WOPdHnjUeb-fc3inZZDGcrQbH0tb8bt7rJ-xQG21JHfhU16djbWAlxlaJjaXG9mFZ4QSBtLGhBQzSqesw2VnOx7OixlcHBEziiIEC6QUeai2FxvYTN56UF0yBoWiLyhD63jeRhv9bQLZ__FJWeCgfDBe4I9IZZHbocrgZdEKP99bCRH5m9YB5PVXFn1dc--xD0Ed5WYISt7p2xTE-mORRa4VCEt0iV0ylxOzXCWJlNGFowpphQspIHxvSuawuFl_IKggml78drDia7Y8mheb0Vg
Content-Type: application/json

{
  "name":"palace",
  "phone": "phone1",
  "address": 
    {
      "zipcode": "string",
      "street1": "string",
      "street2": "string",
      "country": "string",
      "state": "string"
    }
  
}


###
GET http://localhost:8002/v1/users/64b5a7428dfe3fa4c0d0662c
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2TTBsOHFPWU5mMFlGUmhTMm1JTiJ9.eyJpc3MiOiJodHRwczovL2Rldi1mdXVleWdrcno4MWJpcml4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJaZEVvRVE5ZlJsc09YMms2QWNkNzBiYkZVVjBJMnZXWUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnQudGlja2V0ZXguY29tIiwiaWF0IjoxNjg5NjE4NzkwLCJleHAiOjE2ODk3MDUxOTAsImF6cCI6IlpkRW9FUTlmUmxzT1gyazZBY2Q3MGJiRlVWMEkydldZIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.JiFE-Oxq0LvFWaz2zlV2W3ABpqPepmvY3NPwyuMk2nDJeggEHK0JhK7akancXl6WOPdHnjUeb-fc3inZZDGcrQbH0tb8bt7rJ-xQG21JHfhU16djbWAlxlaJjaXG9mFZ4QSBtLGhBQzSqesw2VnOx7OixlcHBEziiIEC6QUeai2FxvYTN56UF0yBoWiLyhD63jeRhv9bQLZ__FJWeCgfDBe4I9IZZHbocrgZdEKP99bCRH5m9YB5PVXFn1dc--xD0Ed5WYISt7p2xTE-mORRa4VCEt0iV0ylxOzXCWJlNGFowpphQspIHxvSuawuFl_IKggml78drDia7Y8mheb0Vg
Content-Type: application/json 

###
GET http://localhost:8000/v1/users
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2TTBsOHFPWU5mMFlGUmhTMm1JTiJ9.eyJpc3MiOiJodHRwczovL2Rldi1mdXVleWdrcno4MWJpcml4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJaZEVvRVE5ZlJsc09YMms2QWNkNzBiYkZVVjBJMnZXWUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnQudGlja2V0ZXguY29tIiwiaWF0IjoxNjg5NjE4NzkwLCJleHAiOjE2ODk3MDUxOTAsImF6cCI6IlpkRW9FUTlmUmxzT1gyazZBY2Q3MGJiRlVWMEkydldZIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.JiFE-Oxq0LvFWaz2zlV2W3ABpqPepmvY3NPwyuMk2nDJeggEHK0JhK7akancXl6WOPdHnjUeb-fc3inZZDGcrQbH0tb8bt7rJ-xQG21JHfhU16djbWAlxlaJjaXG9mFZ4QSBtLGhBQzSqesw2VnOx7OixlcHBEziiIEC6QUeai2FxvYTN56UF0yBoWiLyhD63jeRhv9bQLZ__FJWeCgfDBe4I9IZZHbocrgZdEKP99bCRH5m9YB5PVXFn1dc--xD0Ed5WYISt7p2xTE-mORRa4VCEt0iV0ylxOzXCWJlNGFowpphQspIHxvSuawuFl_IKggml78drDia7Y8mheb0Vg
Content-Type: application/json 

###
GET http://localhost:8000/v1/adventures
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2TTBsOHFPWU5mMFlGUmhTMm1JTiJ9.eyJpc3MiOiJodHRwczovL2Rldi1mdXVleWdrcno4MWJpcml4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJaZEVvRVE5ZlJsc09YMms2QWNkNzBiYkZVVjBJMnZXWUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnQudGlja2V0ZXguY29tIiwiaWF0IjoxNjg5NjE4NzkwLCJleHAiOjE2ODk3MDUxOTAsImF6cCI6IlpkRW9FUTlmUmxzT1gyazZBY2Q3MGJiRlVWMEkydldZIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.JiFE-Oxq0LvFWaz2zlV2W3ABpqPepmvY3NPwyuMk2nDJeggEHK0JhK7akancXl6WOPdHnjUeb-fc3inZZDGcrQbH0tb8bt7rJ-xQG21JHfhU16djbWAlxlaJjaXG9mFZ4QSBtLGhBQzSqesw2VnOx7OixlcHBEziiIEC6QUeai2FxvYTN56UF0yBoWiLyhD63jeRhv9bQLZ__FJWeCgfDBe4I9IZZHbocrgZdEKP99bCRH5m9YB5PVXFn1dc--xD0Ed5WYISt7p2xTE-mORRa4VCEt0iV0ylxOzXCWJlNGFowpphQspIHxvSuawuFl_IKggml78drDia7Y8mheb0Vg
Content-Type: application/json 

###
GET http://localhost:8001/v1/venues
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2TTBsOHFPWU5mMFlGUmhTMm1JTiJ9.eyJpc3MiOiJodHRwczovL2Rldi1mdXVleWdrcno4MWJpcml4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJaZEVvRVE5ZlJsc09YMms2QWNkNzBiYkZVVjBJMnZXWUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnQudGlja2V0ZXguY29tIiwiaWF0IjoxNjg5NjE4NzkwLCJleHAiOjE2ODk3MDUxOTAsImF6cCI6IlpkRW9FUTlmUmxzT1gyazZBY2Q3MGJiRlVWMEkydldZIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.JiFE-Oxq0LvFWaz2zlV2W3ABpqPepmvY3NPwyuMk2nDJeggEHK0JhK7akancXl6WOPdHnjUeb-fc3inZZDGcrQbH0tb8bt7rJ-xQG21JHfhU16djbWAlxlaJjaXG9mFZ4QSBtLGhBQzSqesw2VnOx7OixlcHBEziiIEC6QUeai2FxvYTN56UF0yBoWiLyhD63jeRhv9bQLZ__FJWeCgfDBe4I9IZZHbocrgZdEKP99bCRH5m9YB5PVXFn1dc--xD0Ed5WYISt7p2xTE-mORRa4VCEt0iV0ylxOzXCWJlNGFowpphQspIHxvSuawuFl_IKggml78drDia7Y8mheb0Vg
Content-Type: application/json 

###
GET http://localhost:8000/v1/adventures/64b5a3662081f9b35d4b57f1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2TTBsOHFPWU5mMFlGUmhTMm1JTiJ9.eyJpc3MiOiJodHRwczovL2Rldi1mdXVleWdrcno4MWJpcml4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJaZEVvRVE5ZlJsc09YMms2QWNkNzBiYkZVVjBJMnZXWUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnQudGlja2V0ZXguY29tIiwiaWF0IjoxNjg5NjE4NzkwLCJleHAiOjE2ODk3MDUxOTAsImF6cCI6IlpkRW9FUTlmUmxzT1gyazZBY2Q3MGJiRlVWMEkydldZIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.JiFE-Oxq0LvFWaz2zlV2W3ABpqPepmvY3NPwyuMk2nDJeggEHK0JhK7akancXl6WOPdHnjUeb-fc3inZZDGcrQbH0tb8bt7rJ-xQG21JHfhU16djbWAlxlaJjaXG9mFZ4QSBtLGhBQzSqesw2VnOx7OixlcHBEziiIEC6QUeai2FxvYTN56UF0yBoWiLyhD63jeRhv9bQLZ__FJWeCgfDBe4I9IZZHbocrgZdEKP99bCRH5m9YB5PVXFn1dc--xD0Ed5WYISt7p2xTE-mORRa4VCEt0iV0ylxOzXCWJlNGFowpphQspIHxvSuawuFl_IKggml78drDia7Y8mheb0Vg
Content-Type: application/json 

###

PUT http://localhost:8000/v1/adventures/64b5a3662081f9b35d4b57f1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2TTBsOHFPWU5mMFlGUmhTMm1JTiJ9.eyJpc3MiOiJodHRwczovL2Rldi1mdXVleWdrcno4MWJpcml4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJaZEVvRVE5ZlJsc09YMms2QWNkNzBiYkZVVjBJMnZXWUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnQudGlja2V0ZXguY29tIiwiaWF0IjoxNjg5NjE4NzkwLCJleHAiOjE2ODk3MDUxOTAsImF6cCI6IlpkRW9FUTlmUmxzT1gyazZBY2Q3MGJiRlVWMEkydldZIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.JiFE-Oxq0LvFWaz2zlV2W3ABpqPepmvY3NPwyuMk2nDJeggEHK0JhK7akancXl6WOPdHnjUeb-fc3inZZDGcrQbH0tb8bt7rJ-xQG21JHfhU16djbWAlxlaJjaXG9mFZ4QSBtLGhBQzSqesw2VnOx7OixlcHBEziiIEC6QUeai2FxvYTN56UF0yBoWiLyhD63jeRhv9bQLZ__FJWeCgfDBe4I9IZZHbocrgZdEKP99bCRH5m9YB5PVXFn1dc--xD0Ed5WYISt7p2xTE-mORRa4VCEt0iV0ylxOzXCWJlNGFowpphQspIHxvSuawuFl_IKggml78drDia7Y8mheb0Vg
content-type:application/json

{
  "name": "string111",
  "description": "string111",
  "tickets": [
    {
      "capacity": 0,
      "type": "string"
    }
  ],
  "venue": {
    "name": "string",
    "address": {
      "zipcode": "string",
      "street1": "string",
      "street2": "string",
      "country": "string",
      "state": "string" 
    },
    "phone": "string"
  }
}

###
DELETE http://localhost:8000/v1/adventures/64b5a3662081f9b35d4b57f1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2TTBsOHFPWU5mMFlGUmhTMm1JTiJ9.eyJpc3MiOiJodHRwczovL2Rldi1mdXVleWdrcno4MWJpcml4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJaZEVvRVE5ZlJsc09YMms2QWNkNzBiYkZVVjBJMnZXWUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnQudGlja2V0ZXguY29tIiwiaWF0IjoxNjg5NjE4NzkwLCJleHAiOjE2ODk3MDUxOTAsImF6cCI6IlpkRW9FUTlmUmxzT1gyazZBY2Q3MGJiRlVWMEkydldZIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.JiFE-Oxq0LvFWaz2zlV2W3ABpqPepmvY3NPwyuMk2nDJeggEHK0JhK7akancXl6WOPdHnjUeb-fc3inZZDGcrQbH0tb8bt7rJ-xQG21JHfhU16djbWAlxlaJjaXG9mFZ4QSBtLGhBQzSqesw2VnOx7OixlcHBEziiIEC6QUeai2FxvYTN56UF0yBoWiLyhD63jeRhv9bQLZ__FJWeCgfDBe4I9IZZHbocrgZdEKP99bCRH5m9YB5PVXFn1dc--xD0Ed5WYISt7p2xTE-mORRa4VCEt0iV0ylxOzXCWJlNGFowpphQspIHxvSuawuFl_IKggml78drDia7Y8mheb0Vg
Content-Type: application/json 
