POST /v1/tickets/te2s1/ada/11
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2TTBsOHFPWU5mMFlGUmhTMm1JTiJ9.eyJpc3MiOiJodHRwczovL2Rldi1mdXVleWdrcno4MWJpcml4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJaZEVvRVE5ZlJsc09YMms2QWNkNzBiYkZVVjBJMnZXWUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnQudGlja2V0ZXguY29tIiwiaWF0IjoxNjg5NjE4NzkwLCJleHAiOjE2ODk3MDUxOTAsImF6cCI6IlpkRW9FUTlmUmxzT1gyazZBY2Q3MGJiRlVWMEkydldZIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.JiFE-Oxq0LvFWaz2zlV2W3ABpqPepmvY3NPwyuMk2nDJeggEHK0JhK7akancXl6WOPdHnjUeb-fc3inZZDGcrQbH0tb8bt7rJ-xQG21JHfhU16djbWAlxlaJjaXG9mFZ4QSBtLGhBQzSqesw2VnOx7OixlcHBEziiIEC6QUeai2FxvYTN56UF0yBoWiLyhD63jeRhv9bQLZ__FJWeCgfDBe4I9IZZHbocrgZdEKP99bCRH5m9YB5PVXFn1dc--xD0Ed5WYISt7p2xTE-mORRa4VCEt0iV0ylxOzXCWJlNGFowpphQspIHxvSuawuFl_IKggml78drDia7Y8mheb0Vg

{
    "Credit_Card_TX_ID":"aaaaaaaaa",
    "Quantity":4
}

###

GET /v1/tickets/te2s1/ada/11
Host: localhost:8080
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6Ilh2TTBsOHFPWU5mMFlGUmhTMm1JTiJ9.eyJpc3MiOiJodHRwczovL2Rldi1mdXVleWdrcno4MWJpcml4LnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJaZEVvRVE5ZlJsc09YMms2QWNkNzBiYkZVVjBJMnZXWUBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9pbnQudGlja2V0ZXguY29tIiwiaWF0IjoxNjg5NjE4NzkwLCJleHAiOjE2ODk3MDUxOTAsImF6cCI6IlpkRW9FUTlmUmxzT1gyazZBY2Q3MGJiRlVWMEkydldZIiwiZ3R5IjoiY2xpZW50LWNyZWRlbnRpYWxzIn0.JiFE-Oxq0LvFWaz2zlV2W3ABpqPepmvY3NPwyuMk2nDJeggEHK0JhK7akancXl6WOPdHnjUeb-fc3inZZDGcrQbH0tb8bt7rJ-xQG21JHfhU16djbWAlxlaJjaXG9mFZ4QSBtLGhBQzSqesw2VnOx7OixlcHBEziiIEC6QUeai2FxvYTN56UF0yBoWiLyhD63jeRhv9bQLZ__FJWeCgfDBe4I9IZZHbocrgZdEKP99bCRH5m9YB5PVXFn1dc--xD0Ed5WYISt7p2xTE-mORRa4VCEt0iV0ylxOzXCWJlNGFowpphQspIHxvSuawuFl_IKggml78drDia7Y8mheb0Vg

###

PATCH v1/reservations/metadata/newsar/capacities/vip
Host: localhost:8080
Content-Type: application/json

{
    "availability":10002
}

###
POST /reservations/metadata/newsar/capacities/
Host: localhost:8080
Content-Type: application/json

{
    "type":"lapop",
    "availability":30
}

###

POST /reservations/newsar/capacities/vip/users/12345678
Host: localhost:8080
Content-Type: application/json

{
    "quantity":1
} 
###
GET /reservations/newsar/capacities/vip/users/12345678
Host: localhost:8080
Content-Type: application/json

###

PATCH /reservations/newsar/capacities/vip/users/1234567/status/reserved 
Host: localhost:8080
Content-Type: application/json

###

PATCH /reservations/newsar/capacities/vip/users/123456/status/canceled 
Host: localhost:8080
Content-Type: application/json

