POST /reservations
Host: localhost:8080
Content-Type: application/json

{
    "adventure_id": "news",
    "status":1,
    "capacities":[
        {
            "type":"vip",
            "availability":1000
        },
        {
            "type":"popular",
            "availability":1000
        },
        {
            "type":"free",
            "availability":100
        }
    ]
}

###

GET /reservations/news
Host: localhost:8080
Content-Type: application/json

###

PATCH /reservations/news/capacities/vip
Host: localhost:8080
Content-Type: application/json

{
    "availability":10002
}

###
POST /reservations/news/capacities/
Host: localhost:8080
Content-Type: application/json

{
    "type":"lapop",
    "availability":30
}

###

POST /reservations/news/capacities/vip/users/123456
Host: localhost:8080
Content-Type: application/json

{
    "quantity":1
} 
###

PATCH /reservations/news/capacities/vip/users/12345/status/reserved 
Host: localhost:8080
Content-Type: application/json

###

PATCH /reservations/news/capacities/vip/users/123456/status/canceled 
Host: localhost:8080
Content-Type: application/json

