POST /reservations/metadata
Host: localhost:8080
Content-Type: application/json

{
    "adventure_id": "new1sar",
    "status":1,
    "capacities":[
        {
            "type":"vip",
            "availability":1000
        },
        {
            "type":"popular",
            "availability":1000
        },
        {
            "type":"free",
            "availability":100
        }
    ]
}

###

GET /reservations/metadata/new1sar
Host: localhost:8080
Content-Type: application/json

###

PATCH /reservations/metadata/newsar/capacities/vip
Host: localhost:8080
Content-Type: application/json

{
    "availability":10002
}

###
POST /reservations/metadata/newsar/capacities/
Host: localhost:8080
Content-Type: application/json

{
    "type":"lapop",
    "availability":30
}

###

POST /reservations/newsar/capacities/vip/users/12345678
Host: localhost:8080
Content-Type: application/json

{
    "quantity":1
} 
###
GET /reservations/newsar/capacities/vip/users/12345678
Host: localhost:8080
Content-Type: application/json

###

PATCH /reservations/newsar/capacities/vip/users/1234567/status/reserved 
Host: localhost:8080
Content-Type: application/json

###

PATCH /reservations/newsar/capacities/vip/users/123456/status/canceled 
Host: localhost:8080
Content-Type: application/json

