FROM python:3.11.4-slim-bookworm

WORKDIR /code
ENV VIRTUALENV=/home/realpython/venv
RUN python3 -m venv $VIRTUALENV
ENV PATH="$VIRTUALENV/bin:$PATH"
COPY ./requirements.txt /code/requirements.txt
COPY ./common/tiklib /code/common/tiklib
COPY ./common/pyproject.toml /code/common
RUN pip install --no-cache-dir --upgrade -r requirements.txt
WORKDIR /code/common
RUN pip install .
WORKDIR /code
COPY ./adventures/app /code/app
COPY ./adventures/.env /code/
COPY ./adventures/logging.yaml /code/
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]